
jupyter-server:
	#SYMPY_USE_CACHE=no PYTHONPATH=../src/:../../../programming-contests/competitive-programming/python-libs/ jupyter-notebook --no-browser --port=5901 --ip=150.217.37.116
	PYTHONPATH=../src/:../../../programming-contests/competitive-programming/python-libs/ jupyter-notebook --no-browser --port=5901 --ip=150.217.37.116
	#jupyter-notebook --no-browser --port=5901 --ip=150.217.37.116

