
jupyter-server:
	PYTHONPATH=../src/:../../../programming-contests/competitive-programming/python-libs/ jupyter-notebook --no-browser --port=5901 --ip=150.217.37.116
	#jupyter-notebook --no-browser --port=5901 --ip=150.217.37.116

tests:
	python3.5 -m doctest utils.py
	python3.5 -m doctest recurrences.py
